language: java
addons:
  sonarcloud:
    organization: un1ckq
    token:
      secure: VYY4GdrqxTJa94McgcKbXqdFexUoRAG1wAz3cYuAaZUsrqpPopIf767xJpt68r6J07fVQ+ablnlZy0jakaCcLuA2tiPmC9SHgcO7RCctkD+kggnejHLNobX81B3bJD+FxLZgRHKUbcrvbXxggJ3ZmFdTH1jpkOEONsVT4shiMlBHdastKIYw/ggsKKzqRnyAQFqlY3+lMEmYirLWXF34yrIImK20dGl7x0tBx/VcRoG/sDy0EPK37dWiwQUUGXJge7CASPCR5npPfPVQGe7dN/5imQbgmQ0byk5zspVc1xqZfTFPny4QetH799zxrneMxQnQUgfCEdrXZoDnksDKBYXTKFEyDB8wZ2zCoYmu66kJLK7215GEP9CLqQFVVLBphyXEKdAOElZ1nHiVpsQO2ojSN3dMBhLVMK67diYOyG0LiVVbG8xXGG4DlaDryQgbOZ1rlsjH7ZQtPJQSjvDxO2Hk1f4oi3pWyU1CoSqNSFr2SBnNdSiuHEDSZFKchczDz8QV8kdxaPX7wBZBulIaNxLjoB/3PdUqAxUvqrM4/fDcNrTFck4TfBvoQK+gK0AeSTf0T8dv4MwrVJTEaKxhj0fK7IiVMCMKZ5p2AULeUYH3ZEpGaa+Uj2tmz6T6iA4YnugG8ctIYjKMe+OgDxujDZqSPNVOWAViiUZqAKq2pkc=

script:
- "./gradlew clean jar jacocoTestReport sonarqube"

deploy:
  provider: heroku
  api_key:
    secure: e6atyO9hTbTOWC2y+vWYuKr6uE8ld3caUx85VtVaGzuSWZYKh/SpQqT5Y7jzhL4LDMqf5n5jpkSM99x93Zt69z8n1ontK1dfMBn8CkeAxKitdVwYLbObUNRBn9756Pqs+1Af4AzfD8XL4y9588RAn2Daw0leoIRI83EputiULwWgHbwyWJGMEWM+6PqdqWg1JjVmcU8KZoZe0VGTdE9B8Cuy0zV3XgPpurntPxOcr9J9RtapZnpGzUKi1/s7BpNeNrQbvtl3BZB9Oj/jAVraz06nq/Cm+kkaQi5iLRcydKeO6qTpQJv5p4l2YxYaz/yedEbH6YK0ZKr54YSh/TaFldiZ7x53e/SpXNFHwj8rYGI+oJvsVEGIhLkJMc7/YwJy/brR+OIt1NEhiEzFDCQY2Lu5FWOdMqnlTBAmZNqS3meE+OnOyfBaxcWKdKOs5Z7KcieNTmZzsT4wjiFX8yx1xxVqVVYmnAa86u1HL/XjkP+3SGzFXEdSY2IYDDiiRR0MSbLDCafwIF1sqQiigqzrUW2ZOIpetXuBgNRaEB8/SL0JH/VPhUnhMwEN6eRhK8P5sUAFIkaUQfrLrIeNDjYnZ+69/g9Ppzxb9Nd1HZ+gYW4Ph5HxzN7Gw2MUdwQUIVRWblOxt0ZIhT772nZhMhoT8HEw8lmrrc/PivPz5PzFDAM=
